<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => 'Доступ запрещен',
    'Access to content management' => 'Доступ к управлению контентом',
    'Check your email for further instructions.' => 'Проверьте указанную почту для дальнейших инструкций.',
    'Created' => 'Создано',
    'Email' => '',
    'Follow the link below to activate your account' => 'Следуйте по сслыке ниже для активации учетной записи',
    'Follow the link below to reset your password' =>  'Следуйте по сслыке ниже для восстановления пароля',
    'Group' => 'Группа',
    'Hello' => 'Здравствуйте',
    'If you forgot your password you can' => 'Если вы забыли пароль, вы можете',
    'Incorrect username or password.' => 'Не верное имя пользователя или пароль.',
    'Login' => 'Вход',
    'You can log in using the social network.' => 'Можно войти, используя социальную сеть.',
    'Modified' => 'Изменено',
    'Name' => 'Имя',
    'New password was saved.' => 'Новый пароль сохранен.',
    'Password' => 'Пароль',
    'Password reset token cannot be blank.' => 'Восстановительный токен не может быть пустым.',
    'Remember me' => 'Запомнить меня',
    'Repeat the passport' => 'Повторите пароль',
    'Request password reset' => 'Запрос изменения пароля',
    'Reset password' => 'Изменить пароль',
    'Robot: Account activating for ' => 'Робот: Активность с учетной записью ',
    'Robot: Password reset for ' => 'Робот: Восстановление пароля для ',
    'Save' => 'Сохранить',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем изменить пароль для данного email.',
    'Spam protection code' => 'Код защиты от  спама',
    'Status' => 'Статус',
    'Submit' => 'Отправить',
    'The requested model does not exist.' => 'Запрошенная модель не существует.',
    'There is no user with such email.' => 'Пользователя с таким email не существует.',
    'This email address has already been taken.' => 'Данный email уже занят.',
    'This page is for registered users. If it\'s not about you, you can go through a simple' => 
        'Эта страница для зарегистрированных пользователей. Если это не про вас, то вы можете воспользоваться ссылкой ',
    'This username has already been taken.' => 'Это имя пользователя уже занято.',
    'To signup' => 'Зарегистрироваться',
    'Update' => 'Изменения',
    'User activation token cannot be blank.' => 'Токен активации пользователя не может быть пустым.',
    'User {name} can\'t be activated!' => 'Пользователь {name} не может быть активирован!',
    'User {name} is successfully activated.' => 'Пользователь {name} успешно активирован.',
    'User with {email} for {client} have been exist, but not linked to each other. Try to login with name and password.' => 
        'Пользователь с {email} для {client} уже существует, но не связан с данной сетью. Войдите с помощью bvtyb и пароля.',
    'Users' => 'Пользователи',
    'Wrong password reset token.' => 'Не верный токен восстановления пароля.',
    'Wrong user activation token.' => 'Не верный токен активации пользователя.',
    'You are registered, but you belong to a group that is not allowed to enter this part of the site.' => 
        'Вы зарегистрированы, но принадлежите к группе, которой не разрешен вход в эту часть сайта',
    'You can request a password change if you have already registered.' => 'Вы можете запросить изменение пароля если уже были зарегистрированы.',
    'registration' => 'регистрация',
    'reset it' => 'восстановить его',
    '{name}\'s profile was successfully updated.' => 'Профайл {name} успешно обновлен.',
    '{name}, thank you for registering on the {website} website, check email, to complete the procedure.' => 
		'{name}, спасибо за регистрацию на сайте {website}, проверьте, указанную при регистрации, почту для завершения процедуры.',
];
